using System;
using System.IO;
using System.Text;
using Firebase.Firestore;
using Firebase.Extensions;

[FirestoreData]
public struct FirebaseUserData
{
    [FirestoreProperty]
    public byte[] binary { get; set; }
    [FirestoreProperty]
    public long saveDate { get; set; }
    [FirestoreProperty]
    public string userid { get; set; }
    [FirestoreProperty]
    public string binary_str { get; set; }
}

public class TpFirebaseDataProp
{
    public static readonly string dbPath = "USERDATA/";

    public void Init()
    {
        var firestore = FirebaseFirestore.DefaultInstance;
        firestore.Settings.PersistenceEnabled = false;
    }

    public void UpLoadData(System.Action<bool> OnEnd)
    {
        var firestore = FirebaseFirestore.DefaultInstance;
        if (TpPlatformLoginProp.fUser != null)
        {
            byte[] saveData = null;
            var filePath = GameRoot.Instance.UserData.GetSaveFilePath();

            if (File.Exists(filePath))
            {
                saveData = File.ReadAllBytes(filePath);
            }

            if (saveData == null)
                return;

            BpLog.Log($"binary str : {Convert.ToBase64String(saveData)}");

            var userData = new FirebaseUserData()
            {
                binary = saveData,
                saveDate = TimeSystem.GetCurTime().Ticks,
                userid = TpPlatformLoginProp.fUser.UserId,
                binary_str = Convert.ToBase64String(saveData)
            };

            firestore.Document($"{dbPath}{TpPlatformLoginProp.fUser.UserId}")
            .SetAsync(userData).ContinueWithOnMainThread(task =>
            {
                UnityEngine.Assertions.Assert.IsNull(task.Exception);
                OnEnd?.Invoke(task.IsCompletedSuccessfully);
            }); ;
        }
    }

    public void GetSaveDate(Action<long> OnReturn)
    {
        var firestore = FirebaseFirestore.DefaultInstance;
        if (TpPlatformLoginProp.fUser != null)
        {
            firestore.Document($"{dbPath}{TpPlatformLoginProp.fUser.UserId}")
                        .GetSnapshotAsync().ContinueWithOnMainThread(task =>
                        {
                            UnityEngine.Assertions.Assert.IsNull(task.Exception);

                            if (task.Result.Exists)
                            {
                                var userData = task.Result.ConvertTo<FirebaseUserData>();
                                OnReturn?.Invoke(userData.saveDate);
                            }
                            else
                            {
                                OnReturn?.Invoke(0);
                            }
                        });
        }
    }

    public void DownLoadData(Action OnEnd)
    {
        var firestore = FirebaseFirestore.DefaultInstance;
        if (TpPlatformLoginProp.fUser != null)
        {
            firestore.Document($"{dbPath}{TpPlatformLoginProp.fUser.UserId}")
                        .GetSnapshotAsync().ContinueWithOnMainThread(task =>
                        {
                            UnityEngine.Assertions.Assert.IsNull(task.Exception);

                            if (task.Result.Exists)
                            {
                                var userData = task.Result.ConvertTo<FirebaseUserData>();

                                var filePath = GameRoot.Instance.UserData.GetBackUpSaveFilePath("backup");
                                if (string.IsNullOrEmpty(userData.binary_str))
                                {
                                    File.WriteAllBytes(filePath, userData.binary);
                                }
                                else
                                {
                                    File.WriteAllBytes(filePath, Convert.FromBase64String(userData.binary_str));
                                }
                            }
                            OnEnd?.Invoke();
                        });

        }
    }

    public void EditorDownLoadData(Action OnEnd)
    {
#if UNITY_EDITOR
        var binary = "UAAAAAAASgC4AAAAAABEAEAAcABsAGgAUABYAGQATACMAJAAlAA0AJgAKACgACQAIABIAAAAOAAYABQACAAAAAQAAACkAKgAnACsALAAtABKAAAABQAAAOCndwRO4N0IAAAAAD0AAAAAAAAAAABQQAMAAAAVAAAAAAhHvzjh3QgAAAAABAAAAAAAAAAAkHBAeAAAAAMAAADEIAAA/////zD0i+ZH4N0Ipqbnhv8EAAAAAAAANBEAAKgVAACMIAAAUJVNj4/g3QgAAAAAAwAAAKgAAAC4AAAAwAkAALANAAC0DQAAzA0AAIgOAADEDgAA5A4AALAPAADwDwAAlBAAAMQQAADUEAAACQAAAGQAAABYAAAATAAAAEAAAAA0AAAAKAAAABwAAAAQAAAABAAAAAIAAAAxMQAAAQAAADIAAAACAAAAMTAAAAEAAAA5AAAAAQAAADcAAAABAAAAMwAAAAEAAAA0AAAAAQAAADEAAAABAAAAOAAAAEDg//8AAQEBBAAAAAIAAABlbgAAQAAAAPAIAADICAAAqAgAAHwIAABYCAAAMAgAABAIAADoBwAAxAcAAJgHAAB4BwAAVAcAADAHAAAQBwAA7AYAAMgGAACkBgAAgAYAAFwGAAA4BgAAFAYAAPAFAADMBQAAqAUAAIQFAABUBQAALAUAAAgFAADUBAAAsAQAAIwEAABoBAAASAQAACgEAAAEBAAA4AMAALwDAACcAwAAeAMAAFQDAAAwAwAADAMAAOgCAADIAgAApAIAAIACAABgAgAAPAIAABgCAAD0AQAA0AEAAKwBAACIAQAAZAEAAEABAAAcAQAA+AAAANQAAACwAAAAlAAAAHAAAABMAAAAKAAAAAQAAAB44f//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8zXzQAAJjh//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzNfMwAAuOH//wgAAAABAAAADAAAAENQX0dlYXJUcnVjawAAAADY4f//CAAAAAEAAAAPAAAAQ1BfU3VwZXJHcmluZGVyAPjh//8IAAAAAQAAAAYAAABDUF9EREQAABDi//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzNfMgAAquT//wQAAAASAAAAU3RhZ2VGYWlsZWRDb3VudF8xAABQ4v//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8zXzEAAHDi//8IAAAAAQAAAA8AAABOZXdTa2lsbFBvcHVwXzMAkOL//wgAAAABAAAADwAAAFN0YXJ0U3RhZ2VfMl8xMACw4v//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8yXzkAANDi//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfOAAA8OL//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMl83AAAQ4///CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8yXzYAAKrl//8EAAAAEgAAAFN0YWdlRmFpbGVkQ291bnRfNQAAyuX//wQAAAAQAAAASXRlbVVzZUluU3RhZ2VfMgAAAABw4///CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8yXzUAAJDj//8IAAAAAQAAAAsAAABBZFBhc3NPcmRlcgCs4///CAAAAAEAAAAPAAAAVHJhaW5pbmdBZFdhdGNoAEbm//8EAAAAEgAAAFN0YWdlRmFpbGVkQ291bnRfNAAAZub//wQAAAAPAAAAV2F2ZUZhaWxlZENvdW50AAjk//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfNAAAKOT//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMl8zAABI5P//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8yXzIAAGjk//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfMQAAiOT//wgAAAABAAAADwAAAE5ld1NraWxsUG9wdXBfMgCo5P//CAAAABkAAAAIAAAAT3BlbkNhcmQAAAAAxOT//wgAAAABAAAADwAAAFN0YXJ0U3RhZ2VfMV8xMADk5P//CAAAABEAAAAOAAAATHVja3lTcGluQ291bnQAAATl//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfOQAAJOX//wgAAAABAAAACQAAAFBhc3NDeWNsZQAAAEDl//8IAAAABAAAAAkAAABXaW5TdHJlYWsAAABc5f//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8xXzgAAHzl//8IAAAAAQAAAA4AAABGaXJzdEx1Y2t5U3BpbgAAnOX//wgAAAABAAAADAAAAE5ld0J1ZmZQb3B1cAAAAAC85f//CAAAAAEAAAAfAAAAQWRkQnVyc3RGaXJlQmxvY2tTdGFydGVyUGFja2FnZQDs5f//CAAAAAEAAAAOAAAAU3RhcnRlclBhY2thZ2UAAAzm//8IAAAAAgAAABIAAABCdXlJbkFwcENvdW50VG90YWwAADDm//8IAAAAAQAAABgAAABGaXJzdFN0YXJ0ZXJQYWNrYWdlUG9wdXAAAAAAXOb//wgAAAAIAAAADAAAAEludGVyQWRDb3VudAAAAAB85v//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8xXzcAAJzm//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfNgAAvOb//wgAAAABAAAADwAAAE5ld1NraWxsUG9wdXBfMQDc5v//CAAAAAEAAAAPAAAATm9BZHNQb3B1cFNob3duAHbp//8EAAAAEAAAAEl0ZW1Vc2VJblN0YWdlXzEAAAAAHOf//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMV81AAA85///CAAAAAgAAAAMAAAAQWRXYXRjaENvdW50AAAAAFzn//8IAAAAAQAAAA4AAABBZGRBZFJvY2tCbG9jawAAfOf//wgAAAABAAAADAAAAEZyZWVBZGRCbG9jawAAAACc5///CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8xXzQAALzn//8IAAAAAQAAAAsAAABSZXZpZXdQb3B1cADY5///CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8xXzMAAPjn//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfMgAAGOj//wgAAAABAAAACQAAAEZpcnN0RWNwbQAAADTo//8IAAAAAQAAABUAAABGaXJzdFN0YXJ0QmF0dGxlQ291bnQAAABc6P//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8xXzEAAPbq//8EAAAAFgAAAFN0YWdlQ2xlYXJBbGxUaW1lQ291bnQAABrr//8EAAAADQAAAFRyeVN0YWdlQ2xlYXIAAAC86P//CAAAAB8AAAATAAAAQ2hhbGxlbmdlU3RhZ2VDb3VudADg6P//CAAAAAEAAAAOAAAARW5lcmd5VW5sb2NrZWQAAADp//8IAAAABAAAABYAAABGaXJzdERheUdhbWVFbnRlckNvdW50AAAo6f//CAAAAAIAAAAJAAAAUmFjZUN5Y2xlAAAAROn//wgAAAACAAAAEwAAAFNob3BHZXRBZFNpbHZlckNvaW4AaOn//wgAAAABAAAABAAAAEluaXQAAAAAGAAAANADAACoAwAAiAMAAFwDAAAwAwAABAMAAOACAAC0AgAAlAIAAGgCAAA8AgAAEAIAAOABAAC0AQAAiAEAAFwBAAA8AQAAEAEAAOQAAAC4AAAAjAAAAFwAAAAwAAAABAAAAOTp//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzNfNAAM6v//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8zXzUANOr//wgAAAABAAAAGAAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMl8xMAAAAABg6v//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8zXzEAiOr//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMl85ALDq//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzJfNgDY6v//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8yXzUAeu3//wQAAAAPAAAAU2tpbGxVc2VDb3VudF8yABzr//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzJfNABE6///CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8yXzIAbOv//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMl8xAJTr//8IAAAAAQAAABgAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfMTAAAAAAwOv//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMV85AOjr//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfOAAQ7P//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8xXzYAsu7//wQAAAAPAAAAU2tpbGxVc2VDb3VudF8xAFTs//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfNQB87P//CAAAACgAAAAPAAAARmlyc3REYXlMb2dUaW1lAJzs//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfNADE7P//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8xXzMA7Oz//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMV8yABTt//8IAAAA8wAAAAgAAABNX1Jldl8wNQAAAAAw7f//CAAAAGoJAAAQAAAARmlyc3REYXlQbGF5VGltZQAAAABU7f//CAAAAKgMAAANAAAAU3RhZ2VQbGF5VGltZQAAAO7v//8BAAAAdv3//yEAAAAAAAAABAAAAAYAAABQbGF5ZXIAAAYAAACsAAAAhAAAAFwAAABEAAAAHAAAAAQAAADW////AgAAAAEAAAABAAAAAQAAALL///8IAAAAAQAAAAEAAAABAAAAAAAOABQABAAIAAAADAAQAA4AAAADAAAAAQAAAAEAAAABAAAA6v///wQAAAABAAAAAQAAAAEAAAAAAA4AFgAEAAgAAAAMABAADgAAAAEAAAABAAAAAQAAAAEAAAAAAA4AEAAAAAQAAAAIAAwADgAAAAEAAAABAAAAAQAAAAQAAAAwAAAAJAAAABQAAAAEAAAAbO7//wQAAAABAAAAeO7//wMAAAACAAAA/vD//wIAAACM7v//AQAAAAcAAAACAAAAFAAAAAQAAACk7v//AgAAAAEAAACw7v//AQAAAAEAAAAKAAAApAAAAJAAAAB8AAAAbAAAAFgAAABEAAAANAAAACQAAAAUAAAABAAAAOju//8GAAAAAQAAAPTu//8BAAAAAQAAAADv//8FAAAAAQAAAAzv//8RAAAAAQAAABL///8KAAAAAgAAAAIAAAAi////DgAAAAEAAAABAAAAOO///wsAAAADAAAAPv///xQAAAACAAAAAwAAAE7///8EAAAAAgAAAAQAAABe////DAAAAAIAAAABAAAABAAEAAQAAAAQACAABAAIABQAAAAMABAAEAAAAAcAAAAbAAAAEgAAABAAAABAcqFF3ffdCAAAAAAIAAAAAAAAAAEAAAACAAAAAwAAAAQAAAAFAAAABgAAAAcAAADQ7///AgAAAAQAAAAFAAAAeAAAAFgAAAA4AAAAJAAAAAQAAADC////BgAAAAEAAACgAQAAAAAKABAABAAIAAwACgAAAAQAAAACAAAA+QAAAO7///8IAAAAAQAAAKQBAAAAAAoAEgAEAAgADAAKAAAACQAAAAIAAAD7AAAAAAAKAAwAAAAEAAgACgAAAAMAAAD/////FAAuABgABAAAAAgADAAQACAAFAAUAAAAMgAAAAEAAAADAAAADwAAAAQAAABg4twHj+DdCNAa7IuP4N0IAAAAAAAABgAMAAQABgAAAMBnP26Q4N0ICAAQAAcACAAIAAAAAAAAASCZ7BoT4d0IGwAAAFQEAAAsBAAADAQAAOADAAC0AwAAiAMAAGQDAAA4AwAAGAMAAOwCAADAAgAAlAIAAGQCAAA4AgAADAIAAOABAADAAQAAlAEAAGgBAAA8AQAAEAEAAOAAAAC0AAAAiAAAAFwAAAAwAAAABAAAAEDx//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzRfMgBo8f//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF80XzEAkPH//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfM185ALjx//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzNfNADg8f//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8zXzUACPL//wgAAAABAAAAGAAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMl8xMAAAAAA08v//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8zXzEAXPL//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMl85AITy//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzJfNgCs8v//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8yXzUATvX//wQAAAAPAAAAU2tpbGxVc2VDb3VudF8yAPDy//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzJfNAAY8///CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8yXzIAQPP//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMl8xAGjz//8IAAAAAQAAABgAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfMTAAAAAAlPP//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMV85ALzz//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfOADk8///CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8xXzYAhvb//wQAAAAPAAAAU2tpbGxVc2VDb3VudF8xACj0//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfNQBQ9P//CAAAACgAAAAPAAAARmlyc3REYXlMb2dUaW1lAHD0//8IAAAAAQAAABcAAABBY3F1aXJlZFN0YWdlUmV3YXJkXzFfNACY9P//CAAAAAEAAAAXAAAAQWNxdWlyZWRTdGFnZVJld2FyZF8xXzMAwPT//wgAAAABAAAAFwAAAEFjcXVpcmVkU3RhZ2VSZXdhcmRfMV8yAOj0//8IAAAAig0AAAgAAABNX1Jldl8wNQAAAAAE9f//CAAAAGsJAAAQAAAARmlyc3REYXlQbGF5VGltZQAAAAAo9f//CAAAAOgRAAANAAAAU3RhZ2VQbGF5VGltZQAAAEwAAAC8CgAAjAoAAGwKAABACgAAHAoAAPQJAADQCQAApAkAAIAJAABUCQAANAkAABAJAADsCAAAzAgAAKgIAACECAAAYAgAADwIAAAYCAAA9AcAAMgHAACkBwAAgAcAAFwHAAA4BwAACAcAAOAGAAC8BgAAiAYAAGQGAABABgAAHAYAAAAGAADgBQAAvAUAAJgFAAB0BQAAVAUAADAFAAAMBQAA6AQAAMQEAACgBAAAfAQAAFgEAAA0BAAAFAQAAPADAADMAwAAqAMAAIQDAABgAwAAPAMAABgDAAD0AgAA0AIAAKwCAACIAgAAZAIAAEgCAAAkAgAAAAIAANwBAAC4AQAAlAEAAHABAABMAQAAKAEAAAQBAADgAAAAvAAAAJgAAAB0AAAAUAAAACwAAAAEAAAAfPb//wgAAAABAAAAEgAAAFN0YWdlRmFpbGVkQ291bnRfMwAAoPb//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfNF8zAADA9v//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV80XzIAAOD2//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzRfMQAAAPf//wgAAAABAAAADwAAAE5ld1NraWxsUG9wdXBfNACa+f//BAAAABMAAABTdGFnZUZhaWxlZENvdW50XzEwAED3//8IAAAAAQAAAA8AAABTdGFydFN0YWdlXzNfMTAAYPf//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfM185AACA9///CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8zXzgAAKD3//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzNfNwAAwPf//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfM182AADg9///CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8zXzUAAAD4//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzNfNAAAIPj//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfM18zAABA+P//CAAAAAEAAAAMAAAAQ1BfR2VhclRydWNrAAAAAGD4//8IAAAAAQAAAA8AAABDUF9TdXBlckdyaW5kZXIAgPj//wgAAAABAAAABgAAAENQX0RERAAAmPj//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfM18yAAAy+///BAAAABIAAABTdGFnZUZhaWxlZENvdW50XzEAANj4//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzNfMQAA+Pj//wgAAAABAAAADwAAAE5ld1NraWxsUG9wdXBfMwAY+f//CAAAAAEAAAAPAAAAU3RhcnRTdGFnZV8yXzEwADj5//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfOQAAWPn//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMl84AAB4+f//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8yXzcAAJj5//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfNgAAMvz//wQAAAASAAAAU3RhZ2VGYWlsZWRDb3VudF81AABS/P//BAAAABAAAABJdGVtVXNlSW5TdGFnZV8yAAAAAPj5//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfNQAAGPr//wgAAAABAAAACwAAAEFkUGFzc09yZGVyADT6//8IAAAAAQAAAA8AAABUcmFpbmluZ0FkV2F0Y2gAzvz//wQAAAASAAAAU3RhZ2VGYWlsZWRDb3VudF80AAB0+v//CAAAAAEAAAAPAAAAV2F2ZUZhaWxlZENvdW50AJT6//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfNAAAtPr//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMl8zAADU+v//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8yXzIAAPT6//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzJfMQAAFPv//wgAAAABAAAADwAAAE5ld1NraWxsUG9wdXBfMgA0+///CAAAACIAAAAIAAAAT3BlbkNhcmQAAAAAUPv//wgAAAABAAAADwAAAFN0YXJ0U3RhZ2VfMV8xMABw+///CAAAABoAAAAOAAAATHVja3lTcGluQ291bnQAAJD7//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfOQAAsPv//wgAAAABAAAACQAAAFBhc3NDeWNsZQAAAEb+//8EAAAACQAAAFdpblN0cmVhawAAAOT7//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfOAAABPz//wgAAAABAAAADgAAAEZpcnN0THVja3lTcGluAAAk/P//CAAAAAEAAAAMAAAATmV3QnVmZlBvcHVwAAAAAET8//8IAAAAAQAAAB8AAABBZGRCdXJzdEZpcmVCbG9ja1N0YXJ0ZXJQYWNrYWdlAHT8//8IAAAAAQAAAA4AAABTdGFydGVyUGFja2FnZQAAlPz//wgAAAACAAAAEgAAAEJ1eUluQXBwQ291bnRUb3RhbAAAuPz//wgAAAABAAAAGAAAAEZpcnN0U3RhcnRlclBhY2thZ2VQb3B1cAAAAADk/P//CAAAAAsAAAAMAAAASW50ZXJBZENvdW50AAAAAAT9//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfNwAAJP3//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMV82AABE/f//CAAAAAEAAAAPAAAATmV3U2tpbGxQb3B1cF8xAGT9//8IAAAAAQAAAA8AAABOb0Fkc1BvcHVwU2hvd24AAAAGAAgABAAGAAAABAAAABAAAABJdGVtVXNlSW5TdGFnZV8xAAAAAKz9//8IAAAAAQAAAA4AAABTdGFydFN0YWdlXzFfNQAAzP3//wgAAAALAAAADAAAAEFkV2F0Y2hDb3VudAAAAADs/f//CAAAAAEAAAAOAAAAQWRkQWRSb2NrQmxvY2sAAAz+//8IAAAAAQAAAAwAAABGcmVlQWRkQmxvY2sAAAAALP7//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMV80AABM/v//CAAAAAEAAAALAAAAUmV2aWV3UG9wdXAAaP7//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMV8zAACI/v//CAAAAAEAAAAOAAAAU3RhcnRTdGFnZV8xXzIAAKj+//8IAAAAAQAAAAkAAABGaXJzdEVjcG0AAADE/v//CAAAAAEAAAAVAAAARmlyc3RTdGFydEJhdHRsZUNvdW50AAAA7P7//wgAAAABAAAADgAAAFN0YXJ0U3RhZ2VfMV8xAAAM////CAAAAAEAAAAWAAAAU3RhZ2VDbGVhckFsbFRpbWVDb3VudAAANP///wgAAAACAAAADQAAAFRyeVN0YWdlQ2xlYXIAAABU////CAAAACoAAAATAAAAQ2hhbGxlbmdlU3RhZ2VDb3VudAB4////CAAAAAEAAAAOAAAARW5lcmd5VW5sb2NrZWQAAJj///8IAAAABQAAABYAAABGaXJzdERheUdhbWVFbnRlckNvdW50AADA////CAAAAAIAAAAJAAAAUmFjZUN5Y2xlAAAA3P///wgAAAACAAAAEwAAAFNob3BHZXRBZFNpbHZlckNvaW4ACAAMAAQACAAIAAAACAAAAAEAAAAEAAAASW5pdAAAAAAQAAwACAAFAAYAAAAAAAcAEAAAAAABAQEEAAAAAgAAAGVuAAAmAAAAc3RhcnRlcl9wYWNrYWdlXzEwMDAzO2l0ZW1fcGFja2FnZV8xMDEAAA==";
        var filePath = GameRoot.Instance.UserData.GetBackUpSaveFilePath("backup");
        File.WriteAllBytes(filePath, Convert.FromBase64String(binary));

        OnEnd?.Invoke();
#endif
    }
}
